import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-screen items-center">
          <div className="flex-grow flex flex-col p-4 lg:w-5/12 md:w-7/12 w-full">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
