import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

async function getData() {
  const res = await fetch("http://localhost:4000/api/task");

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function Home() {
  const res = await getData();
  // console.log("res: ", res);

  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>Todo app</h1>
    </main>
  );
}
