import Link from "next/link";
import { Metadata } from "next";
import { FaEdit, FaTrash, FaPlus, FaInfo, FaCircle } from "react-icons/fa";
import DeleteButton from "@/components/delete-btn";
import { revalidatePath } from "next/cache";
import { MdDone, MdDoneAll } from "react-icons/md";
import { Task, updateTask } from "./actions";
import StatusButton from "@/components/status-btn";
import { getServerSession } from "next-auth";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

const apiUrl =
  process.env.NEXT_PUBLIC_API_ENDPOINT || "http://localhost:4000/api/";

async function getTasks() {
  const res = await fetch(`${apiUrl}/task`, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${cookies().get("currentUser")?.value}`,
    },
    next: { revalidate: 10 },
  });

  // if (!res.ok) {
  //   // This will activate the closest `error.js` Error Boundary
  //   throw new Error("Failed to fetch data");
  // }

  // Recommendation: handle errors manually
  return res;
}

async function deleteTask(id: number) {
  const res = await fetch(`${apiUrl}/task/${id}`, {
    method: "DELETE",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${cookies().get("currentUser")?.value}`,
    },
  });

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to delete task");
  }

  return res.json();
}

function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(" ");
}

export default async function Task() {
  const res = await getTasks();

  const session = await getServerSession();

  // console.log("session from task: ", session);
  async function handleStatus(id: number, task: Task) {
    "use server";
    const res = await updateTask(id, {
      ...task,
      status: "COMPLETE",
    });
    if (res) {
      revalidatePath("/task", "page");
    }
  }

  async function handleDelete(id: number) {
    "use server";
    const res = await deleteTask(id);
    if (res) {
      revalidatePath("/task", "page");
    }
  }

  if (!res) {
    return <div>No data</div>;
  }

  if (res.status === 401) {
    return <div>Unauthorized</div>;
  }

  if (res.status === 403) {
    return <div>Forbidden</div>;
  }

  const data = await res.json();

  if (res instanceof Error) {
    return <div>{res.message}</div>;
  }

  return (
    <>
      <h1 className="text-2xl font-bold mb-4">Todo List</h1>
      <Link href={"/task/create"} passHref>
        <button
          className="bg-blue-500 text-white py-2 px-4 mb-4 rounded-md shadow-md flex items-center justify-center mt-4 hover:bg-blue-600 w-full"
          aria-label="Create new task"
        >
          <FaPlus className="mr-2" />
          Add New Task
        </button>
      </Link>
      <ul className="mt-3 grid gap-5 ">
        {data.map((task: any) => (
          <li
            key={task.id}
            className="col-span-1 flex rounded-md shadow-lg border-r border-t border-slate-300 dark:border-slate-400"
          >
            <StatusButton
              className={classNames(
                task.status === "ACTIVE" ? "bg-green-500" : "bg-blue-500",
                "flex lg:w-16 md:w-10 w-6 flex-shrink-0 items-center justify-center rounded-l-md text-sm font-medium text-white"
              )}
              handleClick={handleStatus}
              id={task.id}
              task={task}
              disabled={task.status === "COMPLETE"}
            >
              {task.status === "ACTIVE" ? <MdDone /> : <MdDoneAll />}
            </StatusButton>
            <article className="flex w-full items-center justify-between">
              <div className="flex flex-col px-4">
                <h2 className="font-bold">{task.title}</h2>
                <p className="text-gray-600 dark:text-gray-400">
                  {task.description}
                </p>
              </div>
              <div>
                <Link href={`/task/${task.id}`} passHref>
                  <button
                    className="text-blue-500 dark:text-blue-300 rounded-md p-2 hover:bg-blue-100 dark:hover:bg-blue-900"
                    aria-label="More info"
                  >
                    <FaInfo />
                  </button>
                </Link>
                <Link href={`/task/edit/${task.id}`} passHref>
                  <button
                    className="text-blue-500 dark:text-blue-300 rounded-md p-2 hover:bg-blue-100 dark:hover:bg-blue-900"
                    aria-label="Edit task"
                  >
                    <FaEdit />
                  </button>
                </Link>
                <DeleteButton
                  className="text-red-500 dark:text-red-300 rounded-md p-2 hover:bg-red-100 dark:hover:bg-red-900"
                  aria-label="Delete task"
                  handleClick={handleDelete}
                  id={task.id}
                >
                  <FaTrash />
                </DeleteButton>
              </div>
            </article>
          </li>
        ))}
      </ul>
    </>
  );
}
