import Link from "next/link";
import { Metadata } from "next";
import { revalidatePath } from "next/cache";
import { FaEdit, FaTrash, FaPlus, FaInfo } from "react-icons/fa";
import DeleteButton from "@/components/delete-btn";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

async function getTasks() {
  const res = await fetch("http://localhost:4000/api/task", {
    method: "GET",
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  // Recommendation: handle errors manually
  return res.json();
}

async function deleteTask(id: number) {
  const res = await fetch(`http://localhost:4000/api/task/${id}`, {
    method: "DELETE",
  });

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to delete task");
  }

  return res.json();
}

export default async function Task() {
  const res = await getTasks();
  // console.log("res: ", JSON.stringify(res, null, 2));

  async function handleDelete(id: number) {
    "use server";
    const res = await deleteTask(id);
    if (res) {
      revalidatePath("/");
    }
  }

  if (!res) {
    return <div>No data</div>;
  }

  if (res instanceof Error) {
    return <div>{res.message}</div>;
  }

  return (
    <div className="grid justify-items-center mt-10">
      <main className="flex flex-col items-center p-24 w-fit bg-white dark:bg-gray-800 shadow-md dark:shadow-none rounded-lg">
        <h1 className="text-2xl font-bold mb-4">Todo app</h1>
        <Link href={"/task/create"} passHref>
          <button
            className="bg-blue-500 text-white py-2 px-4 mb-4 rounded-md shadow-md flex items-center justify-center mt-4 hover:bg-blue-600 w-full"
            aria-label="Create new task"
          >
            <FaPlus className="mr-2" />
            Add New Task
          </button>
        </Link>
        <ul className="grid gap-2 dark:bg-gray-800">
          {res.map((task: any) => (
            <li
              key={task.id}
              className="bg-white dark:bg-gray-700 p-4 rounded-md flex items-center justify-between gap-10"
            >
              <div className="">
                <h2 className="font-bold">{task.title}</h2>
                <p className="text-gray-600 dark:text-gray-400">
                  {task.description}
                </p>
              </div>
              <div>
                <Link href={`/task/${task.id}`} passHref>
                  <button
                    className="text-blue-500 dark:text-blue-300 rounded-md p-2 hover:bg-blue-100 dark:hover:bg-blue-900"
                    aria-label="More info"
                  >
                    <FaInfo />
                  </button>
                </Link>
                <Link href={`/task/edit/${task.id}`} passHref>
                  <button
                    className="text-blue-500 dark:text-blue-300 rounded-md p-2 hover:bg-blue-100 dark:hover:bg-blue-900"
                    aria-label="Edit task"
                  >
                    <FaEdit />
                  </button>
                </Link>
                <DeleteButton
                  className="text-red-500 dark:text-red-300 rounded-md p-2 hover:bg-red-100 dark:hover:bg-red-900"
                  aria-label="Delete task"
                  handleClick={handleDelete}
                  id={task.id}
                >
                  <FaTrash />
                </DeleteButton>
              </div>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}
